import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GetServerSideProps } from "next";
import { getDatabase } from "../src/database";
import Link from "next/link";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const data = await getDatabase();
  const games = await data
    .db("myFirstDatabase")
    .collection("games")
    .find()
    .toArray();
  const gamesStringinfy = JSON.stringify(games);
  const gamesParse = JSON.parse(gamesStringinfy);

  console.log(gamesParse);

  return {
    props: {
      games: gamesParse,
    },
  };
};
type GamesProps = {
  games: any;
};
const Games: React.FC<GamesProps> = ({ games }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next Game Catalogue!</h1>
        <div className={styles.grid}>
          {games.map((game: any, index: any) => {
            return (
              <Link href="#" key={index}>
                <a className={styles.card}>
                  <h2> {game.name} &rarr;</h2>
                </a>
              </Link>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>Made by Miora</footer>
    </div>
  );
};

export default Games;
